### ISSUE TITLE
404 link in XIP-5

### ISSUE THREAD

**Issue by martindufort** [xmtp/XIPs#10]
The [Reference Implementation](https://github.com/xmtp/XIPs/blob/main/XIPs/xip-5-message-content-types.md#reference-implementation) section provides a link which is not publicly accessible.

**Comment by mg0716** [comment]
@martindufort good call out! We haven't yet made that repo public, but I'll see what we can do to get some Gists up and running in the meantime. Will keep this issue active until it's been resolved.

**Comment by mkobetic** [comment]
Just to make it clear, the implementation has been merged into the SDK yesterday, so the latest version of the npm package has it.

**Comment by mkobetic** [comment]
I dumped the diff that was merged into a gist https://gist.github.com/mkobetic/949157c79807286c32bf466968248556

**Comment by galligan** [comment]
> Just to make it clear, the implementation has been merged into the SDK yesterday, so the latest version of the npm package has it.

@mkobetic does this mean this issue can be closed?

**Comment by mkobetic** [comment]
> > Just to make it clear, the implementation has been merged into the SDK yesterday, so the latest version of the npm package has it.
> 
> @mkobetic does this mean this issue can be closed?

I believe the link in question was https://github.com/xmtp/xmtp-js/pull/68 (from the XIP), and since we made 
xmtp/xtmp-js repo public, I'd say this should be resolved.
